name: test

on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/test.yml'

env:
  go-version: '1.16'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
      - run: go test -cover
        if: matrix.os == 'linux' && matrix.arch == 'amd64'

  test-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: go build
      - run: go test -cover -tags windows

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          args: --issues-exit-code=0
          only-new-issues: true
